### ISSUE TITLE
Provide Python and JavaScript packages

### ISSUE THREAD

**Issue by GraemeWatt** [svenkreiss/unicodeit#11]
Firstly, thanks for providing such a useful tool!

Motivated by a [tweet](https://twitter.com/KyleCranmer/status/1255299195478724608?s=20) from @cranmer, I just made a commit (HEPData/hepdata@461967e6639e7278da5af6bfeae900305499f9bf) that uses UnicodeIt to convert LaTeX tags in the titles of high-energy physics publications so they can be automatically tweeted (https://twitter.com/HEPData) whenever data is added to the [hepdata.net](https://www.hepdata.net) repository.  I copied the `unicodeit.py` file into the HEPData code, which is not an ideal solution.

Even though `unicodeit.py` is a simple script with only one function (`replace`), it would make it easier for other tools to use if it was provided as a Python package on [PyPI](https://pypi.org), so it could be installed with `pip install unicodeit`.

I can think of a use case (HEPData/hepdata#149) for `unicodeit.js` where we have had problems with MathJax.  Again, instead of copying `unicodeit.js` into our code, a better solution might be to release it as a JavaScript package on [npm](https://www.npmjs.com), so it could be installed with `npm install unicodeit`.

**Comment by svenkreiss** [comment]
Great point. All my other projects are on pypi and npm.
I am working on reviving the dev tools for this project. 
It's a bigger effort than just packaging but it's a start: #14

**Comment by beta-ziliani** [comment]
If you end up making the package, I will happily provide a solution for Linux using [AutoKey](https://github.com/autokey/autokey/).

**Comment by svenkreiss** [comment]
UnicodeIt is now available on PyPI and on NPM. Readme is updated. Please let me know if you encounter any issues. 

Enjoy ☺

**Comment by cranmer** [comment]
Can we close this now?

**Comment by svenkreiss** [comment]
Fine with me. @beta-ziliani please let us know in a new issue if you end up creating a solution with AutoKey for Linux. It seems there is interest.

**Comment by beta-ziliani** [comment]
It seems to be working, thanks!

In case you want to add information about AutoKey in the README, here is my script:

```python
import time
import re
import unicodeit

retCode, latex = dialog.input_dialog("Latex2Unicode", "Write LaTeX text")
if retCode == 0:
  text = unicodeit.replace(latex)
  print(text)
  prev_text = clipboard.get_clipboard()
  clipboard.fill_clipboard(text)
  time.sleep(0.2)
  active = window.get_active_class()
  if active == "emacs.Emacs":
    keyboard.send_keys('<ctrl>+y')
    time.sleep(0.2)
    keyboard.send_keys('<shift>')
  elif active == "gnome-terminal-server.Gnome-terminal":
    keyboard.send_keys('<ctrl>+<shift>+v')
  else:
    keyboard.send_keys('<shift>+<insert>')
  time.sleep(0.2)
  clipboard.fill_clipboard(prev_text)
```

**Comment by cranmer** [comment]
Nice!
