### ISSUE TITLE
Does the python version work?

### ISSUE THREAD

**Issue by beta-ziliani** [svenkreiss/unicodeit#15]
I can't seem to make it work. When I do `unicodeit.replace("a_1")`, I get a list of binary-coded characters with `a` `_` `1`. Am I missing something?

**Comment by svenkreiss** [comment]
Now it should. I have just done a major rewrite. It's also available on pypi now so you can install it in Python with `pip install unicodeit`.

**Comment by svenkreiss** [comment]
Closing for now, but please reopen if there is still an issue for you.
