### ISSUE TITLE
Extend to other emoji

### ISSUE THREAD

**Issue by adavidzh** [svenkreiss/unicodeit#3]
I was wondering if there would be interest in extending `unicodeit` to also include the likes of `\ht`→🎩 (for hat-tip) or `\Jamaica`→🇯🇲 (and other countries).
Or should I just fork and forget?

**Comment by svenkreiss** [comment]
Yes, sounds interesting

**Comment by svenkreiss** [comment]
Hi @adavidzh , did you ever got to work on that? I have just done a major refactor of the whole project (#14) and would be interested to get these new commands supported now.

**Comment by adavidzh** [comment]
Eventually, I [found a big list of Mac text replacements](https://www.funkyspacemonkey.com/macmoji-easy-fast-way-type-emojis-mac) and quit on the whole idea:
![image](https://user-images.githubusercontent.com/4256469/87076133-96ec4f80-c221-11ea-92ce-a1e8abdd7b79.png)

One good thing of these is that they follow across devices. I'll close the issue.

**Comment by svenkreiss** [comment]
Thanks for sharing. I found good resources at that link. Maybe at some I can add an automated completion of some emoji commands :)
