### ISSUE TITLE
Subscript and superscript in latex is not working properly

### ISSUE THREAD

**Issue by anindyasdas** [svenkreiss/unicodeit#30]
In online demo X_{N-1} gives X_N₋₁
X^{N-1} results in  Xᴺ⁻¹

**Comment by svenkreiss** [comment]
This happens when unicodeit doesn't know a subscript. I assume it doesn't know the subscript for N.

**Comment by anindyasdas** [comment]
![sni0](https://user-images.githubusercontent.com/50780535/93860291-81dd7380-fcdc-11ea-88f2-4eb9ac05d9a1.PNG)
 How does one get unicode for this from latex?

**Comment by svenkreiss** [comment]
Few letters are supported by unicode as subscripts last time I checked. This (sort of) works: https://www.unicodeit.net/?word_%7Bj-1%7D
