### ISSUE TITLE
Suppport for \bigcup and \bigcap

### ISSUE THREAD

**Issue by eliasgv3** [svenkreiss/unicodeit#33]
Hi there,
I'm a regular user of unicode.it

I've noticed that on unicode.it there's no support for \bigcup and \bigcap. I know that \cup and \cap already give [∪](https://util.unicode.org/UnicodeJsps/character.jsp?a=222A) and [∩](https://util.unicode.org/UnicodeJsps/character.jsp?a=2229). But unicode has two more characters which I think would fit with the \bigcup and \bigcap LaTeX symbols; they are [⋃](https://util.unicode.org/UnicodeJsps/character.jsp?a=22C3) and [⋂](https://util.unicode.org/UnicodeJsps/character.jsp?a=22C2).

I would be pleased if you could add support to them. 

Thank you.

**Comment by svenkreiss** [comment]
Should be fixed in 0.7.1
