### ISSUE TITLE
Superscripts are not grouped by {...}

### ISSUE THREAD

**Issue by schneiderfelipe** [svenkreiss/unicodeit#37]
Hi, I observed that `^{...}` does not behave as I would expect in LaTeX:

```python3
import unicodeit

print(unicodeit.replace("cm^{-1}"))
# => cm^{−1}

print(unicodeit.replace("cm^-^1"))
# => cm⁻¹
```

Is this expected? [unicodeit.net seems to interpret `^{...}` just fine](https://www.unicodeit.net/?cm%5E%7B-1%7D).

Is there a way I can make this work in Python? Thanks!

**Comment by svenkreiss** [comment]
Thanks for reporting @schneiderfelipe . It should be fixed in the next release.
