### ISSUE TITLE
\neg is broken 

### ISSUE THREAD

**Issue by ylhan** [svenkreiss/unicodeit#38]
`\neg` produces `≠g` when it should be ¬

I believe support was added for ¬ was added in https://github.com/svenkreiss/unicodeit/issues/24 but it detects `\ne` before it detects `\neg` as a whole.

**Comment by ylhan** [comment]
![image](https://user-images.githubusercontent.com/23009089/101232182-0a35a880-367e-11eb-942a-5c1ede6a2114.png)

**Comment by svenkreiss** [comment]
Thanks for reporting @ylhan . This is fixed in 0.7.1.
