### ISSUE TITLE
Some subscript letters do not work

### ISSUE THREAD

**Issue by timotheeandres** [svenkreiss/unicodeit#43]
The following inputs are not converted properly:
- b
- c
- d
- f
- g
- q
- w
- y
- z

![image](https://user-images.githubusercontent.com/25198539/110327400-37e21300-801a-11eb-9dad-f327de86f9e1.png)

![image](https://user-images.githubusercontent.com/25198539/110327375-2bf65100-801a-11eb-8c78-7f5e87c1e633.png)

**Comment by jmigual** [comment]
Hi, unfortunately it looks like the Unicode block for superscripts and subscripts does not contain these letters so there is no way to translate them from latex to Unicode. Have a look at the block here: https://www.compart.com/en/unicode/block/U+2070

**Comment by vvsagar** [comment]
Hello, I love this project! Thanks for making it!

But not having Unicode blocks for superscripts and subscripts of some Latin and Greek letters is sad, I wanted to use this for particles and μ and τ don't have subscripts, so some neutrinos don't look right.

It is a long shot, but I wish Unicode adds them in the version🤞
