### ISSUE TITLE
The “UnicodeIt” service could not be used in Keynote, Pages... 

### ISSUE THREAD

**Issue by foice** [svenkreiss/unicodeit#7]
Hello! this Mac OS Service has been a great help for years, but now it seems to have stop to work in Keynote. It does not work in Pages, but does work in Mail ... strange.
Anyhow, any idea why "The “UnicodeIt” service could not be used."
Thanks for helping and for writing this useful script!

**Comment by svenkreiss** [comment]
I have just done a major rewrite. There is a new way to create the workflow yourself in the readme. I found that to be more stable than sharing a workflow. I hope it works for you.

**Comment by svenkreiss** [comment]
Closing for now, but please reopen if there is still an issue for you.
