### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by HDembinski** [svenkreiss/unicodeit#71]
This is an interesting package, but the lack of development is worrisome. There are bugs open since about two years that seem to be easy to fix. What is the status of this project?

I am considering to fork this project to fix open issues for my application in iminuit.

**Comment by svenkreiss** [comment]
There is only one open pull request and I am still thinking about whether that is a good idea. All others are merged. I wouldn’t call that dead. Feel free to send pull requests if you want. No promises on my response time though. I don’t work in physics anymore and this is a hobby by now. 

It’s open source and you are of course free to fork this project.

**Comment by HDembinski** [comment]
I was referring to old open issues:
https://github.com/svenkreiss/unicodeit/issues/25
https://github.com/svenkreiss/unicodeit/issues/27
https://github.com/svenkreiss/unicodeit/issues/49

This is a more recent one:
https://github.com/svenkreiss/unicodeit/issues/59

I originally came here to report that this code `$D^{\ast\ast}$` does not render correctly when you use the Python module, although it works correctly on the website https://www.unicodeit.net/.

After looking into the implementation, I can see that the Python implementation lacks a parser for simple LaTeX. The basic search-and-replace approach that you currently use is very limited. Fixing this would require a rewrite of this small library.

I decided to use unicodeit anyway, as an optional dependency for iminuit
https://github.com/scikit-hep/iminuit/pull/858
